remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Your App Name
description: Documentation for Your App
show_downloads: false

# Navigation
nav:
  - Home: "index.md"
  - User Guide: "user-guide/index.md"
  - API Reference: "api-reference/index.md"
  - Contributing: "contributing.md"

# Optional: You can add custom CSS for further dark mode adjustments
# custom_css: custom.css