remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Your App Name
description: Documentation for Your App
show_downloads: false

# Navigation
nav:
  - Home: "/"
  - Development Guide: "/development-guide/"
  - Installation: "/installation/"
  - User Guide: "/user-guide/"

# Optional: You can add custom CSS for further dark mode adjustments
# custom_css: custom.css